name: st
description: SnapTrack
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_clean_architecture:
    git:
      url: https://github.com/gurhanadiguzel/Flutter-Clean-Architecture.git

  # Firebase
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  cloud_firestore: ^4.12.2

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  transparent_image: ^2.0.1
  camera: ^0.10.5+5
  flutter_map: ^6.0.1
  latlng: any
  geolocator: ^10.1.0
  flutter_map_location_marker: ^8.0.2
  sliding_up_panel: ^2.0.0+1
  dotted_border: ^2.1.0
  firebase_dynamic_links: ^5.4.6
  vibration: ^1.8.4
  lottie: ^2.7.0
  share_plus: ^7.2.1
  path: ^1.8.0
  maps_launcher: ^2.2.0
  uuid: ^4.3.3
  flutter_slidable: ^3.0.1
  image_picker: ^1.0.7
  geoflutterfire2: ^2.3.15
  infinite_scroll_pagination: ^4.0.0
  custom_refresh_indicator: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#584CF4"
  image: assets/run/splash.png
  android_12:
    image: assets/run/splash.png
    color: "#584CF4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/run/launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
